### PR TITLE
Kernel 5.10.110

### PR DESCRIPTION
**Pull request by WXbet**

### CODE REVIEW

**Comment by persianpros** [comment]
firmware is wrong and is for 5.15.x

**Comment by WXbet** [comment]
From which repo do you pick the toi updates?

**Comment by persianpros** [comment]
https://github.com/raspberrypi/firmware

Last 5.10.x is what I pushed, we need to try 5.15.x

**Comment by WXbet** [comment]
Have a Pi Zero to test it...

**Comment by persianpros** [comment]
I'll create a new branch and let you know when to test it ;)

**Pull request closed without merging**
